
source("Algorithm/sort/bubble_sort.R", encoding = "UTF-8")
source("Algorithm/sort/selection_sort.R", encoding = "UTF-8")
source("Algorithm/sort/insert_sort.R", encoding = "UTF-8")
source("Algorithm/sort/shell_sort.R", encoding = "UTF-8")
source("Algorithm/sort/quick_sort.R", encoding = "UTF-8")
source("Algorithm/sort/merge_sort.R", encoding = "UTF-8")

set.seed(123)
x <- sample(10000)
print("bubble sort")
print(system.time(bubble_sort(x)))
print("selection sort")
print(system.time(selection_sort(x)))
print("insert sort")
print(system.time(insert_sort(x)))
print("shell sort")
print(system.time(shell_sort(x)))
print("quick sort")
print(system.time(quick_sort(x)))
print("merge sort")
print(system.time(merge_sort(x)))
